Remove --offline flag from cargo install command (#7315)
Otherwise cargo throws error when installing on a clean Rust installation 

error: failed to load source for dependency `ethers`

Caused by:
  Unable to update https://github.com/gakonst/ethers-rs?rev=73e5de211c32a1f5777eb5194205bdb31f6a3502#73e5de21

Caused by:
  can't checkout from 'https://github.com/gakonst/ethers-rs': you are in the offline mode (--offline)