Inform users to update in case of error [E0658]
If users try to build/check the project with an older version of rust, it will fail due to this error: `error[E0658]: use of unstable library feature 'map_into_keys_values'`.

It is fixed with `rustup update`